spring.application.name=taskmanager
spring.datasource.url=jdbc:postgresql://localhost:5432/taskmanager
spring.datasource.username=postgres
spring.datasource.password=7016
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080
jwt.secret=thisIsAVeryLongSecretKeyForJWTThatShouldBeAtLeast256BitsLong
jwt.expiration=86400000